services:
  - type: web
    name: library-seat-booking-api
    runtime: node
    buildCommand: npm run render:api:build
    startCommand: npm run render:api:start
    envVars:
      - key: PORT
        value: 4001
      - key: MONGODB_URI
        sync: false
      - key: WEB_APP_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_MOCK_MODE
        value: "true"
      - key: ADMIN_PIN
        sync: false

  - type: web
    name: library-seat-booking-web
    runtime: node
    buildCommand: npm run render:web:build
    startCommand: npm run render:web:start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
